### ISSUE TITLE
Expired Tokens fail to redirect as expected

### ISSUE THREAD

**Issue by mattgi** [bentojs/web#2]
If you return to your web browser and the session has expired this is the response logged.
```
Routing => /dashboard
api-0 Tue, 09 Feb 2016 00:09:16 GMT api:debug 2016-02-09 10:09:16 GET /announcements | Guest
web-2   TypeError: Cannot read property 'getAvatar' of null
web-2       at Sidebar.render (sidebar.jsx:84:55)
```

If you attempt to retrieve data from the API and receive a 401 the error is about /logout not having a render method so the redirection in place is not working. Typically you would remove the token (logout) and then redirect back to the homepage, not have a route for logging out so Im not sure how this is to be handled.

**Comment by Kodemon** [comment]
Yeah this should be moved into the authentication module and just have that route onwards to a configured after logout route. So we go simply `this.auth.logout()`

**Comment by Kodemon** [comment]
fixed
