### ISSUE TITLE
Page Refresh (dev) requires login

### ISSUE THREAD

**Issue by mattgi** [bentojs/web#3]
In Dev, a page refresh requires the user to sign in again, even though a valid token exists in a cookie.

<img width="1441" alt="screenshot 2016-02-22 12 45 23" src="https://cloud.githubusercontent.com/assets/1043906/13208216/3e7848ba-d962-11e5-9122-e1c866a8ad8b.png">

Is this just because code relies on the iso server for auth and not a browser cookie and, now that we don't use the iso-server in dev, it will always fail? If so, maybe we need to add a config value that code can use to know if it should attempt to `cookie.get` if local.

**Comment by Kodemon** [comment]
fixed
