### ISSUE TITLE
investigate concept of data-views

### ISSUE THREAD

**Issue by mattgi** [bentojs/web#5]
`stores` are based on resources and can be cached based on `query`.

This allows a user to flip between unrelated View Components without a need to refresh data for each view if it is already cached. However, when View Components use the same `resource` chances are that the query for said data will be different, thus clearing the cache and triggering a call to the API to reload the `store`.

An improvement to this would be to allow data to be cached based on a `filter` of the data and only refresh the data when the filter query changes. In a database sense, this would be known as a `data view`.

A working example,
- consider we have 1000 `tasks`.
- 70 `tasks` are assigned to the current user.
- 50 `tasks` are unallocated.

There are 3 View Components - My Tasks, All Tasks, and Unassigned Tasks.

We could define the query for each of these filters, or `data-views`:
```
tasks : {
  all         : null,  
  currentUser : `?assigned=${ this.auth.user.id }`,
  unassigned  : `?assigned=null`  
}
```

This level of abstraction means that data must be accessed via a `data-view`.

By doing this, we maintain data in a `resource store`. This `resource store` stores all data arriving via relay along with the result from each `data-view` query. A View Component then subscribes to a `data-view` to make specific data available.

These `data-views` could also be referenced by model schemas and used by lookups.

A common use case for this would be to allow `user`s to have a different view over the data for each user role.

**Comment by mattgi** [comment]
forgot to add the idea that these `data-views` could be defined on the model.

**Comment by Kodemon** [comment]
Data views will be part of the upcoming `relay.composer` as discussed.
